add schema for user's role
fintegrate-practicum/workers pull request #150
Opened 2024-07-23 15:33 UTC by Efrat6821

2024-07-23 17:14 UTC, Tami-Co submitted a review, later dismissed

2024-07-23 17:19 UTC, buzz-code commented on src/dto/businessRole.dto.ts
> +//   @IsNotEmpty()
אם אין צורך, נא למחוק

2024-07-23 17:19 UTC, buzz-code commented on src/dto/businessRole.dto.ts
> +//   @IsNotEmpty()
כנ״ל

2024-07-23 17:19 UTC, buzz-code commented on src/user/controllers/users.controller.ts
> +
משתמש יכול להיות רשום בכמה עסקים במקביל?

2024-07-24 05:50 UTC, Efrat6821 commented on src/user/controllers/users.controller.ts
> +
כן בכל עסק יכול להיות לו תפקיד אחר
בעסק אחד מנהל
בשני עובד
ובשלישי הוא יכול להיות משתמש
וכו'

2024-07-24 06:23 UTC, Tami-Co approved these changes

2024-07-24 10:18 UTC, buzz-code submitted a review, later dismissed
אני מאשרת את הקוד
אבל האם קיבלתן אישור לדיזיין מנחמי?
לשמור את הנתונים בצורה הזאת?

2024-07-28 09:49 UTC, nechamaLearn requested changes
תשני את כל הmanager לadmin

2024-07-28 09:49 UTC, nechamaLearn commented on src/dto/businessRole.dto.ts
> +    example: 'Manager',
אין manager
יש admin/employee/client

2024-07-28 17:01 UTC, Tami-Co submitted a review, later dismissed

2024-07-29 23:14 UTC, nechamaLearn requested changes

2024-07-29 23:14 UTC, nechamaLearn commented on src/worker/services/workers.service.ts
> +    this.logger.log('create')
תכתבי לוגים קצת יותר משמעותיים
שנוכל לעקוב אחריהם במקרה של נפילה

2024-07-31 22:14 UTC, nechamaLearn approved these changes

2024-07-31 22:14 UTC, nechamaLearn commented on src/app.module.ts
אני מאשרת את הקוד
אבל תוודאי שהשינויים בקובץ הזה תקינים
ואם לא תחזירי אותם למצב שהיו קודם (ידנית...)

2024-08-01 08:09 UTC, Tami-Co approved these changes

2024-08-01 10:04 UTC, michalzrian approved these changes

2024-08-01 10:04 UTC, merged