my branch
fintegrate-practicum/workers pull request #66
Opened 2024-05-21 13:32 UTC by tamarfridlis

Emplyee sign up process:
Creating functions in the controller and a service for updating the details of new employees as well as adding values ​​for new details such as phone.

2024-05-22 20:58 UTC, chanakamin requested changes
לפני שאת מגישה לרויו חוזר תמרגגי ממיין - יש לך קונפליקטים

2024-05-22 20:58 UTC, chanakamin commented on workers-backend/src/schemas/organization.entity.ts
> +
תורידי

2024-05-22 20:58 UTC, chanakamin commented on workers-backend/src/schemas/user.entity.ts
> +  id: string;
למה צריך? הוא לא מוסיף לבד?

2024-05-22 20:58 UTC, chanakamin commented on workers-backend/src/worker/controllers/workers.controller.ts
> +    this.workersService.updateUser(id, data);
try / catch?

2024-05-22 20:58 UTC, chanakamin commented on workers-backend/src/worker/services/workers.service.ts
> +      .findOneAndUpdate({id}, updateUser, { new: true })
מה זה new true?
אין בדיקה על הפרמטרים שמתקבלים?

2024-05-28 06:49 UTC, tamarfridlis commented on workers-backend/src/schemas/user.entity.ts
> +  id: string;
הid הזה הוא אותו דבר כמו הid של הemployee זה אותה רשומה לאותו עובד והם תואמים ה-idים

2024-07-06 22:31 UTC, closed without merging